spring:
  application:
    name:
      image-bff

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./ggomgdb;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        generate_statistics: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

  rabbitmq:
    host: 192.168.45.131
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: auto

  config:
    import:
      - application-security.yml

server:
  servlet:
    session:
      persistent: false

minio:
  url: http://192.168.45.131:9000
  access-key: admin
  secret-key: adminadmin
  bucket: example-bucket

rabbitmq:
  image:
    ocr:
      exchange: image.request
      routing-key: image.ocr.request
    validation:
      exchange: image.request
      routing-key: image.validation.request
    thumbnail:
      exchange: image.request
      routing-key: image.thumbnail.request